### ISSUE TITLE
Adding the Array problem solutions in JavaScript.

### ISSUE THREAD

**Issue by AtharvaMahamuni** [Jiganesh/Loads-Of-Logic#297]
As you guys are adding the Java and Python solutions to the repository I like to add the JavaScript solutions for array-related problems.

@Jiganesh I will contribute with solutions for these problems

- [ ] Two sum problem
- [ ] Move zeros
- [ ] Pascals triangle
- [ ] Three sum

**Comment by Onyelaudochukwuka** [comment]
I'm already working on thus ^_-

**Comment by Sakshi2002-Sinha** [comment]
Hello, Can you please assign this issue to me?
Thanks in advance :)
