### ISSUE TITLE
Problem to find problems and good folder structure

### ISSUE THREAD

**Issue by AtharvaMahamuni** [Jiganesh/Loads-Of-Logic#305]
Hey @Jiganesh,
Do you think we need a good folder structure for the problems to separate them according to language and difficulty levels?

If we arrange problems with different difficulties, types, and languages, it will get easier to find for anyone as well as it will get easier for contributors to find the missing problems and contribute accordingly. 

I would like to do the arrangement if you can assign it to me.

**Comment by AtharvaMahamuni** [comment]
Ya that's cool.

**Comment by Jiganesh** [comment]
Lets create a project website which scraps from Problems readme file and solved list and then searches in that list

**Comment by Sakshi2002-Sinha** [comment]
Hello, Can you please assign this issue to me?
Thanks in advance :)
